[env:lilygo-t-display-16mb]
board = lilygo-t-display-16mb
board_build.partitions = support_files/custom_16Mb.csv
build_src_filter =${env.build_src_filter} +<../boards/lilygo-t-display-16mb>
build_flags =
	${env.build_flags}
	-Iboards/lilygo-t-display-16mb

	-DARDUINO_LILYGO_T_DISPLAY=1
	-DLILYGO_T_DISPLAY=1
	-DT_DISPLAY_16MB=1

	-DPART_16MB=1

	-DROTATION=3
	-DHAS_BTN=1
	-DSEL_BTN=35
	-DUP_BTN=-1
	-DDW_BTN=0
	-DBTN_ACT=LOW
	-DBTN_ALIAS='"Sel"'
	-DMINBRIGHT=190
	-DBACKLIGHT=4
	-DLED=1
	-DLED_ON=HIGH

	-DFP=1
	-DFM=2
	-DFG=3

	-D ST7789_DRIVER
	-D TFT_WIDTH=135
	-D TFT_HEIGHT=240
	-D TFT_CS=5
	-D TFT_DC=16
	-D TFT_RST=23
	-D TFT_MOSI=19
	-D TFT_SCLK=18
	-D TFT_BL=4

	-D GFX_BL=4
	-D TFT_IPS=1
	-D TFT_COL_OFS1=52
	-D TFT_ROW_OFS1=40
	-D TFT_COL_OFS2=53
	-D TFT_ROW_OFS2=40

	-DTFT_BRIGHT_CHANNEL=0
	-DTFT_BRIGHT_Bits=8
	-DTFT_BRIGHT_FREQ=10000

lib_deps =
	${env.lib_deps}
	https://github.com/bmorcelli/ESP32_Button
